import { ReactNode } from "react";
import type { Metadata } from "next";
import {SessionProvider} from "next-auth/react"
import {
  Inter,
  JetBrains_Mono as JetBrainsMono,
  Geist,
} from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

import ThemeProvider from "@/context/Theme";
import { cn } from "@/lib/utils";
import { auth } from "@/auth";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetBrainsMono = JetBrainsMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Qurio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {

  const session = await auth();

  return (
    <html lang="en" className={cn("font-sans", geist.variable)} suppressHydrationWarning>

    <head>
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />   
    </head>

      <SessionProvider session={session}>

      <body
        className={`${inter.variable} ${jetBrainsMono.variable} flex max-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex flex-1 ">{children}</main>
        </ThemeProvider>
        <Toaster />
      </body>
      </SessionProvider>
    </html>
  );
}
